let btn = document.getElementById('open-btn'),
	name = document.getElementsByClassName('name-value'),
	budget = document.getElementsByClassName('budget-value'),
	goods = document.getElementsByClassName('goods-value'),
	items = document.getElementsByClassName('items-value'),
	employers = document.getElementsByClassName('employers-value'),
	discount = document.getElementsByClassName('discount-value'),
	isopen = document.getElementsByClassName('isopen-value'),
	goodsItem = document.getElementsByClassName('goods-item'),
	button = document.getElementsByTagName('button'),
	item = document.querySelector('.choose-item'),
	time = document.querySelector('.time-value'),
	count = document.querySelector('.count-budget-btn'),
	hire = document.querySelectorAll('.hire-employers-item'); 

